apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: multi-service-route
  namespace: gateway-demo
spec:
  parentRefs:
  - name: external-http-gw
  rules:
  - backendRefs:
    - name: hello-svc
      port: 80
      weight: 10
    - name: echo-v2
      port: 80
      weight: 90
